### PR TITLE
Allow to exit full-screen

### LINKED ISSUE #1: Exit fullscreen when clicked again
It would be nice to change the text to "Exit full-screen" after clicking and be able to exit full-screen.

### PR DESCRIPTION
**Pull request by VictorLamoine**
Fixes #1

First `javascript` for me, I don't know how to change the text when the button is clicked :smile:

### CODE REVIEW

**Comment by KTibow** [comment]
Have you tested? Does it work? From a quick look, it looks like you're missing a semicolon.

**Comment by VictorLamoine** [comment]
I have tested it but not this file exactly, you are right; bad copy/paste.

I'm testing on a Raspberry Pi 4 + touch screen.
If I use this button the scrolling (touch screen) doesn't work anymore in Chromium, but it does if I enter full screen with `xdotool key F11`, any idea why?

**Comment by KTibow** [comment]
I don't know. I'm gonna be off the computer for a bit.

**Comment by KTibow** [comment]
Try replacing `body` with `documentElement` and see if that makes scrolling work.

**Comment by VictorLamoine** [comment]
Spot on, PR updated!

**Pull request merged**
